### ISSUE TITLE
Is it possible to make this work with sapper?

### ISSUE THREAD

**Issue by vylink** [beyonk-adventures/svelte-social-auth#6]
Hi there,

thanks for the great extension. Just wondering if is possible to make this work with sapper.

I'm getting the following error:

```
<FacebookAuth> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

**Comment by antony** [comment]
It's written for Sapper. You need to install all of your Sapper dependencies (including this package) as `devDependencies` not `dependencies`

**Comment by vylink** [comment]
@antony, thanks, it works!
